Repository googleapis/python-ndb, pull requests merged in 2019-06, with the labels that each got.

#102 Fix Structured Properties
  src/google/cloud/ndb/model.py
  tests/system/__init__.py
  tests/system/conftest.py
  tests/system/test_crud.py
  tests/unit/test_model.py
Labels: cla: yes

#103 Query repeated structured properties.
  src/google/cloud/ndb/_datastore_query.py
  src/google/cloud/ndb/model.py
  src/google/cloud/ndb/query.py
  tests/system/index.yaml
  tests/system/test_query.py
  tests/unit/test__datastore_query.py
  tests/unit/test_model.py
  tests/unit/test_query.py
Labels: cla: yes

#105 update sphinx version and eliminate all warnings
  docs/conf.py
  noxfile.py
  src/google/cloud/ndb/metadata.py
  src/google/cloud/ndb/model.py
  src/google/cloud/ndb/query.py
  src/google/cloud/ndb/tasklets.py
  test_utils/test_utils/scripts/update_docs.sh
Labels: cla: yes

#111 Fix docs build.
  src/google/cloud/ndb/query.py
Labels: cla: yes

#106 port/correct remaining docs and start narrative effort
  docs/index.rst
  src/google/cloud/ndb/metadata.py
  src/google/cloud/ndb/model.py
  src/google/cloud/ndb/query.py
  src/google/cloud/ndb/stats.py
  src/google/cloud/ndb/tasklets.py
Labels: cla: yes

#97 Added decorators for transactional ops.
  src/google/cloud/ndb/__init__.py
  src/google/cloud/ndb/_transaction.py
  src/google/cloud/ndb/context.py
  src/google/cloud/ndb/exceptions.py
  src/google/cloud/ndb/model.py
  tests/unit/test__transaction.py
  tests/unit/test_context.py
  tests/unit/test_model.py
Labels: :rotating_light:, :rotating_light:, :rotating_light:, cla: yes

#113 Support using the Datastore Emulator.
  src/google/cloud/ndb/client.py
  tests/unit/test_client.py
Labels: cla: yes

#112 Local caching
  src/google/cloud/ndb/_options.py
  src/google/cloud/ndb/context.py
  src/google/cloud/ndb/key.py
  src/google/cloud/ndb/model.py
  tests/unit/test__options.py
  tests/unit/test__transaction.py
  tests/unit/test_context.py
  tests/unit/test_key.py
  tests/unit/test_model.py
Labels: cla: yes

#109 Release python-ndb 0.0.1
  CHANGELOG.md
  README.md
  setup.py
  src/google/cloud/ndb/__init__.py
Labels: autorelease: pending, cla: yes

#116 Implement cache policy.
  docs/conf.py
  docs/context.rst
  docs/index.rst
  src/google/cloud/ndb/client.py
  src/google/cloud/ndb/context.py
  src/google/cloud/ndb/key.py
  src/google/cloud/ndb/model.py
  tests/system/conftest.py
  tests/system/test_crud.py
  tests/unit/test_context.py
Labels: cla: yes

#117 ndb.Expando properties load and save
  src/google/cloud/ndb/model.py
  tests/system/test_crud.py
Labels: cla: yes

#120 add unit tests for _entity_from_ds_entity expando support
  src/google/cloud/ndb/model.py
  tests/system/test_crud.py
  tests/unit/test_model.py
Labels: cla: yes

#119 Fix system test under Datastore Emulator. (Fixes #118)
  src/google/cloud/ndb/client.py
  src/google/cloud/ndb/query.py
  tests/system/conftest.py
  tests/system/test_crud.py
  tests/system/test_query.py
  tests/unit/test_query.py
Labels: cla: yes

#123 add spellcheck sphinx extension to docs build process
  .kokoro/build.sh
  docs/conf.py
  docs/spelling_wordlist.txt
  noxfile.py
  src/google/cloud/ndb/context.py
  src/google/cloud/ndb/key.py
  src/google/cloud/ndb/model.py
  src/google/cloud/ndb/polymodel.py
  src/google/cloud/ndb/query.py
  src/google/cloud/ndb/tasklets.py
  test_utils/test_utils/scripts/update_docs.sh
Labels: cla: yes

#126 Backwards compatibility with older style structured properties.
  src/google/cloud/ndb/model.py
  src/google/cloud/ndb/query.py
  tests/system/test_crud.py
  tests/system/test_query.py
  tests/unit/test_model.py
  tests/unit/test_query.py
Labels: cla: yes

#127 Bugfix: Respect ``_indexed`` flag of properties.
  src/google/cloud/ndb/model.py
  tests/system/test_crud.py
Labels: cla: yes
