Repository googleapis/python-ndb, pull requests merged in 2019-05, with the labels that each got.

#90 Implement ``Model.allocate_ids`` and ``Model.allocate_ids_async``.
  MIGRATION_NOTES.md
  src/google/cloud/ndb/_datastore_api.py
  src/google/cloud/ndb/_options.py
  src/google/cloud/ndb/key.py
  src/google/cloud/ndb/model.py
  tests/system/test_crud.py
  tests/unit/test__datastore_api.py
  tests/unit/test__options.py
  tests/unit/test_model.py
Labels: cla: yes

#91 Model.get by
  src/google/cloud/ndb/model.py
  tests/system/test_crud.py
  tests/unit/test_model.py
Labels: cla: yes

#92 Model.get or insert
  src/google/cloud/ndb/_datastore_api.py
  src/google/cloud/ndb/model.py
  tests/system/test_crud.py
  tests/unit/test__datastore_api.py
  tests/unit/test_model.py
Labels: cla: yes

#94 Three easy Model methods.
  src/google/cloud/ndb/model.py
  tests/unit/test_model.py
Labels: cla: yes

#95 Implement hooks.
  src/google/cloud/ndb/key.py
  src/google/cloud/ndb/model.py
  tests/unit/test_key.py
  tests/unit/test_model.py
Labels: cla: yes

#93 Implement LocalStructuredProperty
  src/google/cloud/ndb/model.py
  tests/unit/test_model.py
Labels: cla: yes

#58 Implemented tasklets.synctasklet
  src/google/cloud/ndb/tasklets.py
  tests/unit/test_tasklets.py
Labels: :rotating_light:, :rotating_light:, :rotating_light:, cla: yes

#86 specify using markdown for long description
  setup.py
Labels: :rotating_light:, :rotating_light:, :rotating_light:

#96 WIP: Model properties
  src/google/cloud/ndb/model.py
  tests/unit/test_model.py
Labels: cla: yes

#98 Fix url in setup.py
  setup.py
Labels: cla: yes

#99 implement expando model
  src/google/cloud/ndb/model.py
  tests/unit/test_model.py
Labels: cla: yes
