Repository googleapis/python-ndb, pull requests merged in 2020-08, with the labels that each got.

#500 build: pick up changes from synthtool
  .kokoro/build.sh
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/fetch_gpg_keys.sh
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/publish-docs.sh
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: cla: yes, context: full

#503 fix: fix concurrency bug in redis cache implementation
  google/cloud/ndb/global_cache.py
  tests/system/test_misc.py
  tests/unit/test_global_cache.py
Labels: cla: yes

#504 feat: use contextvars.ConvextVar instead of threading.local in Python 3
  google/cloud/ndb/context.py
  setup.py
Labels: cla: yes

#508 perf: suppress debug logging in normal operation
  google/cloud/ndb/_datastore_api.py
  google/cloud/ndb/_datastore_query.py
  google/cloud/ndb/_eventloop.py
  google/cloud/ndb/_transaction.py
  google/cloud/ndb/utils.py
  tests/unit/test_utils.py
Labels: cla: yes

#507 build: remove warnings from tests
  google/cloud/ndb/_gql.py
  google/cloud/ndb/_legacy_protocol_buffer.py
  google/cloud/ndb/model.py
  google/cloud/ndb/query.py
  google/cloud/ndb/utils.py
  tests/system/test_query.py
  tests/unit/test__gql.py
  tests/unit/test__legacy_entity_pb.py
  tests/unit/test_query.py
Labels: cla: yes

#511 fix: transparently add sort properties to projection for multiqueries
  google/cloud/ndb/_datastore_query.py
  tests/system/index.yaml
  tests/system/test_query.py
  tests/unit/test__datastore_query.py
Labels: cla: yes

#514 fix: fix format exceptions in `utils.logging_debug`
  google/cloud/ndb/utils.py
  tests/conftest.py
Labels: cla: yes

#520 fix: fix exception handling bug in tasklets
  google/cloud/ndb/tasklets.py
  noxfile.py
  tests/unit/test__retry.py
  tests/unit/test_tasklets.py
  tests/unit/utils.py
Labels: cla: yes

#521 style: upgrade black to latest version, use black default line length
  .flake8
  docs/conf.py
  google/cloud/ndb/_batch.py
  google/cloud/ndb/_cache.py
  google/cloud/ndb/_datastore_api.py
  google/cloud/ndb/_datastore_query.py
  google/cloud/ndb/_datastore_types.py
  google/cloud/ndb/_eventloop.py
  google/cloud/ndb/_gql.py
  google/cloud/ndb/_legacy_entity_pb.py
  google/cloud/ndb/_options.py
  google/cloud/ndb/_transaction.py
  google/cloud/ndb/client.py
  google/cloud/ndb/context.py
  google/cloud/ndb/key.py
  google/cloud/ndb/metadata.py
  google/cloud/ndb/model.py
  google/cloud/ndb/polymodel.py
  google/cloud/ndb/query.py
  google/cloud/ndb/stats.py
  google/cloud/ndb/tasklets.py
  noxfile.py
  tests/system/conftest.py
  tests/system/test_crud.py
  tests/system/test_metadata.py
  tests/system/test_misc.py
  tests/system/test_query.py
  tests/unit/test__cache.py
  tests/unit/test__datastore_api.py
  tests/unit/test__datastore_query.py
  tests/unit/test__gql.py
  tests/unit/test__legacy_entity_pb.py
  tests/unit/test__options.py
  tests/unit/test__transaction.py
  tests/unit/test_context.py
  tests/unit/test_global_cache.py
  tests/unit/test_key.py
  tests/unit/test_model.py
  tests/unit/test_polymodel.py
  tests/unit/test_query.py
  tests/unit/test_stats.py
  tests/unit/test_tasklets.py
  tests/unit/test_utils.py
Labels: cla: yes

#516 perf: improve count query performance for simple queries
  google/cloud/ndb/_datastore_query.py
  google/cloud/ndb/query.py
  tests/unit/test__datastore_query.py
  tests/unit/test_query.py
Labels: api: datastore, cla: yes

#522 chore: start tracking obsolete files
  synth.metadata
Labels: api: datastore, cla: yes, context: full
