Repository googleapis/python-ndb, pull requests merged in 2020-09, with the labels that each got.

#527 fix: make sure `keys_only` ordered multiquery returns keys not entities
  google/cloud/ndb/_datastore_query.py
  tests/system/test_query.py
  tests/unit/test__datastore_query.py
Labels: api: datastore, cla: yes

#528 fix: make optimized `Query.count()` work with the datastore emulator
  google/cloud/ndb/_datastore_query.py
  tests/unit/test__datastore_query.py
Labels: api: datastore, cla: yes

#532 docs: fix type hint for urlsafe
  google/cloud/ndb/key.py
Labels: api: datastore, cla: yes

#531 fix: avoid kind error when using subclasses in local structured properties
  google/cloud/ndb/model.py
  tests/system/test_crud.py
Labels: api: datastore, cla: yes

#536 feat: memcached integration
  .kokoro/build.sh
  .kokoro/docker/docs/Dockerfile
  docs/conf.py
  google/cloud/ndb/__init__.py
  google/cloud/ndb/global_cache.py
  setup.py
  tests/system/conftest.py
  tests/system/test_crud.py
  tests/unit/test_global_cache.py
Labels: api: datastore, cla: yes

#541 build: keep synth in sync
  .kokoro/build.sh
  synth.py
Labels: api: datastore, cla: yes

#542 fix: get_by_id and get_or_insert should use default namespace
  google/cloud/ndb/metadata.py
  google/cloud/ndb/model.py
  tests/system/test_crud.py
  tests/unit/test_metadata.py
  tests/unit/test_model.py
Labels: api: datastore, cla: yes

#548 chore: add replacement pattern to keep memcached in dockerfile
  .kokoro/docker/docs/Dockerfile
  synth.py
Labels: cla: yes

#549 docs: update docker image used for docs generation
  .kokoro/docker/docs/Dockerfile
  synth.metadata
Labels: api: datastore, cla: yes, context: none

#550 build: pick up changes from synthtool (#550)
  .kokoro/populate-secrets.sh
  .kokoro/release/common.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: api: datastore, cla: yes, context: partial
