Repository googleapis/python-ndb, pull requests merged in 2020-10, with the labels that each got.

#553 chore: use BUILD_SPECIFIC_GCLOUD_PROJECT for samples
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.8/common.cfg
  synth.metadata
Labels: cla: yes, context: full

#554 fix: `@non_transactional` decorator was not working correctly with async
  google/cloud/ndb/_datastore_api.py
  tests/system/test_misc.py
Labels: cla: yes

#556 fix: fix a connection leak in RedisCache
  google/cloud/ndb/_cache.py
  google/cloud/ndb/_datastore_api.py
  google/cloud/ndb/global_cache.py
  tests/unit/test__cache.py
  tests/unit/test__datastore_api.py
  tests/unit/test_global_cache.py
Labels: cla: yes

#558 build: support python 3.8 and 3.9
  CONTRIBUTING.rst
  README.md
  noxfile.py
  setup.py
Labels: cla: yes

#537 feat: Transaction propagation using ndb.TransactionOptions
  google/cloud/ndb/_transaction.py
  google/cloud/ndb/context.py
  tests/unit/test__datastore_query.py
  tests/unit/test__transaction.py
  tests/unit/test_context.py
Labels: api: datastore, cla: yes

#560 feat: fault tolerance for global caches
  google/cloud/ndb/_cache.py
  google/cloud/ndb/_datastore_api.py
  google/cloud/ndb/global_cache.py
  tests/unit/test__cache.py
  tests/unit/test_global_cache.py
Labels: cla: yes
