Repository googleapis/python-ndb, pull requests merged in 2020-05, with the labels that each got.

#410 fix: clear context cache on rollback
  google/cloud/ndb/_transaction.py
  tests/system/test_misc.py
Labels: cla: yes

#412 chore: enable context-aware commits
  synth.py
Labels: cla: yes

#413 build: integrate changes from autosynth PR
  .kokoro/build.sh
  .kokoro/publish-docs.sh
  .kokoro/release.sh
Labels: cla: yes

#418 build: get kokoro file generation in sync with synthtool
  synth.py
Labels: cla: yes

#423 fix: more should be boolean in fetch_page call
  google/cloud/ndb/query.py
  tests/unit/test_query.py
Labels: cla: yes

#425 fix: don't rely on duck typing for `_retry.is_transient_error`
  google/cloud/ndb/_retry.py
  tests/unit/test__retry.py
Labels: cla: yes

#428 fix: uniform handling of `projection` argument
  google/cloud/ndb/query.py
  tests/unit/test_model.py
  tests/unit/test_query.py
Labels: cla: yes

#420 fix: Add support for 'name' Key instances to to_legacy_urlsafe
  google/cloud/ndb/key.py
  tests/unit/test_key.py
Labels: cla: yes

#443 fix: refactor transactions to use their own event loops
  google/cloud/ndb/_batch.py
  google/cloud/ndb/_datastore_api.py
  google/cloud/ndb/_eventloop.py
  google/cloud/ndb/_transaction.py
  google/cloud/ndb/tasklets.py
  tests/system/__init__.py
  tests/system/test_crud.py
  tests/system/test_misc.py
  tests/system/test_query.py
  tests/unit/test__datastore_api.py
  tests/unit/test__eventloop.py
  tests/unit/test__transaction.py
  tests/unit/test_tasklets.py
Labels: cla: yes

#444 build: Re-generated to pick up changes from self
  .kokoro/build.sh
  .kokoro/publish-docs.sh
  .kokoro/release.sh
  synth.metadata
Labels: cla: yes, context: none

#451 fix: fix `NotImplementedError` for `get_or_insert` inside a transaction
  google/cloud/ndb/_datastore_api.py
  tests/system/test_crud.py
Labels: cla: yes

#446 fix: make sure datastore key constructor never gets None in a pair
  google/cloud/ndb/key.py
  google/cloud/ndb/model.py
  tests/unit/test_model.py
Labels: cla: yes

#453 fix: respect `_code_name` in `StructuredProperty.__getattr__`
  google/cloud/ndb/model.py
  tests/system/test_query.py
  tests/unit/test_model.py
Labels: cla: yes

#454 fix: all query types should use cache if available
  google/cloud/ndb/_datastore_query.py
  google/cloud/ndb/context.py
  tests/system/test_crud.py
  tests/unit/test__datastore_query.py
Labels: cla: yes

#455 feat: add templates for python samples projects (#506)
  .kokoro/samples/lint/common.cfg
  .kokoro/samples/lint/continuous.cfg
  .kokoro/samples/lint/periodic.cfg
  .kokoro/samples/lint/presubmit.cfg
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.6/continuous.cfg
  .kokoro/samples/python3.6/periodic.cfg
  .kokoro/samples/python3.6/presubmit.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.7/continuous.cfg
  .kokoro/samples/python3.7/periodic.cfg
  .kokoro/samples/python3.7/presubmit.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/samples/python3.8/continuous.cfg
  .kokoro/samples/python3.8/periodic.cfg
  .kokoro/samples/python3.8/presubmit.cfg
  .kokoro/test-samples.sh
  synth.metadata
Labels: cla: yes, context: full
