Repository googleapis/python-ndb, pull requests merged in 2021-01, with the labels that each got.

#559 build(python): samples tests should pass if no samples exist
  .kokoro/test-samples.sh
  synth.metadata
Labels: cla: yes, context: full

#565 docs: correct documentation for `GlobalCache`
  google/cloud/ndb/global_cache.py
Labels: cla: yes

#588 docs: fix typo in example code
  google/cloud/ndb/model.py
Labels: api: datastore, automerge, cla: yes

#591 fix: handle negatives in protobuf deserialization
  google/cloud/ndb/_legacy_protocol_buffer.py
  tests/unit/test__legacy_entity_pb.py
Labels: api: datastore, automerge, cla: yes

#589 fix: make nested retry blocks work for RPC calls
  google/cloud/ndb/_retry.py
  google/cloud/ndb/_transaction.py
  google/cloud/ndb/context.py
  google/cloud/ndb/exceptions.py
  tests/unit/test__retry.py
Labels: api: datastore, cla: yes

#594 docs: fix return type in fetch docstring
  google/cloud/ndb/query.py
Labels: api: datastore, cla: yes
