Repository googleapis/python-ndb, pull requests merged in 2021-02, with the labels that each got.

#597 build: migrate to flakybot
  .kokoro/test-samples.sh
  .kokoro/trampoline_v2.sh
Labels: api: datastore, automerge, cla: yes

#596 fix: handle unpickling between GAE NDB (2.7) to Cloud NDB (3)
  google/cloud/ndb/_legacy_entity_pb.py
  google/cloud/ndb/model.py
  noxfile.py
  tests/conftest.py
  tests/unit/models.py
  tests/unit/test__legacy_entity_pb.py
  tests/unit/test_model.py
Labels: api: datastore, cla: yes

#593 chore: update build scripts
  .kokoro/build.sh
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  synth.metadata
Labels: api: datastore, cla: yes, context: full

#607 fix: fix failing unit test
  tests/unit/test_model.py
Labels: api: datastore, cla: yes

#612 fix: don't return `None` for entities found in queries
  google/cloud/ndb/_datastore_query.py
  tests/system/test_query.py
Labels: api: datastore, cla: yes

#603 feat: retry global cache operations on transient errors
  google/cloud/ndb/_cache.py
  google/cloud/ndb/global_cache.py
  tests/unit/test__cache.py
Labels: api: datastore, cla: yes
