Repository googleapis/python-ndb, pull requests merged in 2021-08, with the labels that each got.

#705 fix: fix bug with concurrent writes to global cache
  google/cloud/ndb/_cache.py
  google/cloud/ndb/_datastore_api.py
  google/cloud/ndb/context.py
  google/cloud/ndb/utils.py
  tests/system/test_crud.py
  tests/unit/test__cache.py
  tests/unit/test__datastore_api.py
  tests/unit/test_concurrency.py
Labels: cla: yes, api: datastore

#707 fix: remove pytz
  setup.py
Labels: cla: yes, api: datastore

#710 chore: generate python samples templates in owlbot.py
  owlbot.py
Labels: cla: yes, api: datastore, automerge, samples

#711 chore: add missing import in owlbot.py
  owlbot.py
Labels: cla: yes, api: datastore, automerge

#709 test: refactor concurrency test using orchestrate
  google/cloud/ndb/_cache.py
  tests/conftest.py
  tests/unit/orchestrate.py
  tests/unit/test_concurrency.py
  tests/unit/test_orchestrate.py
Labels: cla: yes, api: datastore

#714 chore: migrate to main branch
  .kokoro/build.sh
  .kokoro/test-samples-impl.sh
  CONTRIBUTING.rst
  owlbot.py
Labels: cla: yes, api: datastore
