Repository googleapis/python-ndb, pull requests merged in 2023-02, with the labels that each got.

#863 docs: Use cached versions of Cloud objects.inv files
  docs/cloud-core_objects.inv
  docs/conf.py
  docs/datastore_objects.inv
Labels: api: datastore

#858 chore: Add Python 3.11 to Trove classifiers
  setup.py
Labels: api: datastore

#857 tests: Exclude GRPC version that was causing a hang
  noxfile.py
Labels: api: datastore

#868 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: api: datastore, automerge

#869 test: Uncomment some old tests
  tests/unit/test_model.py
Labels: api: datastore

#870 Merge main into multi-db
  .github/CODEOWNERS
  tests/unit/test_model.py
Labels: api: datastore

#871 chore: Fix typo in key.py
  google/cloud/ndb/key.py
Labels: kokoro:run, api: datastore

#872 docs: Note that we support Python 3.11 in CONTRIBUTING file
  CONTRIBUTING.rst
Labels: api: datastore

#873 fix: Query options were not respecting use_cache
  google/cloud/ndb/_datastore_query.py
  tests/system/test_crud.py
  tests/system/test_query.py
  tests/unit/test__datastore_query.py
Labels: api: datastore, automerge
